const meals = [
  {id:1,name:'Himalayan Thali',kitchen:'Thakali Kitchen',description:'Dal, bhat, seasonal tarkari, achar',price:420,category:'Nepali',rating:'4.9',time:'25 min',image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=85'},
  {id:2,name:'Momo Platter',kitchen:'Thakali Kitchen',description:'Steamed chicken momos with tomato achar',price:280,category:'Nepali',rating:'4.8',time:'20 min',image:'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&w=800&q=85'},
  {id:3,name:'Sesame Tofu Bowl',kitchen:'Green Bowl Co.',description:'Crispy tofu, greens, brown rice, sesame glaze',price:390,category:'Healthy',rating:'4.7',time:'30 min',image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=85'},
  {id:4,name:'Creamy Tuscan Pasta',kitchen:'Olive & Hearth',description:'Roasted tomato, garlic, parmesan, basil',price:450,category:'Comfort',rating:'4.9',time:'25 min',image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=85'},
  {id:5,name:'Korean BBQ Rice',kitchen:'Seoul Table',description:'Gochujang beef, kimchi, fried egg, rice',price:520,category:'World food',rating:'4.8',time:'35 min',image:'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=800&q=85'},
  {id:6,name:'Mango Overnight Oats',kitchen:'Green Bowl Co.',description:'Coconut yoghurt, mango, chia, toasted seeds',price:260,category:'Breakfast',rating:'4.6',time:'15 min',image:'https://images.unsplash.com/photo-1517093728432-a0440f8d45af?auto=format&fit=crop&w=800&q=85'}
];
const categories=[['all','✦','All meals'],['Nepali','◒','Nepali'],['Healthy','♧','Healthy'],['Comfort','◉','Comfort'],['World food','✺','World food'],['Breakfast','☼','Breakfast']];
let activeCategory='all'; let search=''; let cart=[];
const money=value=>`Rs. ${value.toLocaleString('en-IN')}`;
const categoryRow=document.querySelector('#categoryRow'); const mealGrid=document.querySelector('#mealGrid');
categoryRow.innerHTML=categories.map(([value,icon,label])=>`<button class="category ${value==='all'?'selected':''}" data-category="${value}"><span>${icon}</span>${label}</button>`).join('');
function filteredMeals(){return meals.filter(meal=>(activeCategory==='all'||meal.category===activeCategory)&&`${meal.name} ${meal.kitchen}`.toLowerCase().includes(search.toLowerCase()))}
function renderMeals(){mealGrid.innerHTML=filteredMeals().map(meal=>`<article class="meal-card"><div class="meal-image"><img src="${meal.image}" alt="${meal.name}"><span class="meal-time">◷ ${meal.time}</span><button class="heart" aria-label="Favourite ${meal.name}">♡</button></div><div class="meal-card-body"><div class="meal-title"><div><h3>${meal.name}</h3><p>${meal.kitchen}</p></div><strong>${money(meal.price)}</strong></div><p class="meal-description">${meal.description}</p><div class="meal-meta"><span>★ ${meal.rating}</span><span>·</span><span>${meal.category}</span><button class="add-button" data-add="${meal.id}">＋ Add</button></div></div></article>`).join('')||'<p class="no-results">No meals match that craving. Try another search.</p>'}
function renderCart(){const count=cart.reduce((sum,item)=>sum+item.quantity,0);const subtotal=cart.reduce((sum,item)=>sum+item.price*item.quantity,0);document.querySelector('#cartCount').textContent=count;document.querySelector('#subtotal').textContent=money(subtotal);document.querySelector('#total').textContent=money(subtotal+99);document.querySelector('#checkoutButton').disabled=!cart.length;document.querySelector('#orderCount').textContent=cart.length+2;document.querySelector('#cartItems').innerHTML=cart.length?cart.map(item=>`<div class="cart-item"><img src="${item.image}" alt=""><div><strong>${item.name}</strong><small>${item.kitchen}</small><div class="quantity"><button data-decrease="${item.id}">−</button><b>${item.quantity}</b><button data-increase="${item.id}">＋</button></div></div><strong>${money(item.price*item.quantity)}</strong></div>`).join(''):`<div class="empty-cart"><span>✦</span><strong>Your bag is waiting</strong><p>Add something delicious from the menu.</p></div>`}
function showToast(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function switchView(view){document.querySelectorAll('.view').forEach(item=>item.classList.remove('active'));document.querySelector(`#${view}View`).classList.add('active');document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===view));document.querySelector('#sidebar').classList.remove('mobile-open');window.scrollTo({top:0,behavior:'smooth'})}
function renderAdmin(){const rows=[['#1048','Maya Shrestha','2 items','Rs. 840','Preparing','preparing'],['#1047','Rajan Karki','3 items','Rs. 1,240','Out for delivery','delivery'],['#1046','Nima Gurung','1 item','Rs. 390','Received','received'],['#1045','Sita Lama','4 items','Rs. 1,680','Preparing','preparing']];document.querySelector('#adminOrders').innerHTML=rows.map(row=>`<tr><td><strong>${row[0]}</strong><small>Today, 10:24</small></td><td>${row[1]}</td><td>${row[2]}</td><td><strong>${row[3]}</strong></td><td><span class="status ${row[5]}">${row[4]}</span></td></tr>`).join('')}
categoryRow.addEventListener('click',event=>{const button=event.target.closest('[data-category]');if(!button)return;activeCategory=button.dataset.category;document.querySelectorAll('.category').forEach(item=>item.classList.toggle('selected',item===button));renderMeals()});
document.querySelector('#searchInput').addEventListener('input',event=>{search=event.target.value;renderMeals()});
mealGrid.addEventListener('click',event=>{const button=event.target.closest('[data-add]');if(!button)return;const meal=meals.find(item=>item.id===Number(button.dataset.add));const existing=cart.find(item=>item.id===meal.id);if(existing)existing.quantity++;else cart.push({...meal,quantity:1});renderCart();document.querySelector('#cartDrawer').classList.add('open');document.querySelector('#scrim').classList.add('show');showToast(`${meal.name} added to your bag`)})
document.querySelector('#cartItems').addEventListener('click',event=>{const increase=event.target.closest('[data-increase]');const decrease=event.target.closest('[data-decrease]');const control=increase||decrease;if(!control)return;const id=Number(control.dataset[increase?'increase':'decrease']);const item=cart.find(entry=>entry.id===id);if(!item)return;if(increase)item.quantity++;else item.quantity--;cart=cart.filter(entry=>entry.quantity>0);renderCart()});
document.querySelectorAll('.nav-item,[data-view="customer"]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.view||'customer')));document.querySelector('#mobileMenu').addEventListener('click',()=>document.querySelector('#sidebar').classList.toggle('mobile-open'));
function closeCart(){document.querySelector('#cartDrawer').classList.remove('open');document.querySelector('#scrim').classList.remove('show')}document.querySelector('#closeCart').addEventListener('click',closeCart);document.querySelector('#scrim').addEventListener('click',closeCart);
document.querySelector('#checkoutButton').addEventListener('click',()=>{closeCart();document.querySelector('#checkoutModal').classList.add('show')});document.querySelector('#closeModal').addEventListener('click',()=>document.querySelector('#checkoutModal').classList.remove('show'));
document.querySelector('#checkoutForm').addEventListener('submit',event=>{event.preventDefault();const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0)+99;cart=[];renderCart();document.querySelector('#checkoutModal').classList.remove('show');switchView('orders');showToast(`Order placed successfully · ${money(total)}`)});
renderMeals();renderCart();renderAdmin();
