const destinations = [
  {slug:'everest-base-camp',name:'Everest Base Camp',region:'Khumbu',days:'14 days',price:'$1,890',type:'classic',tag:'Iconic',image:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=80',intro:'Stand at the foot of the world’s highest mountain on a route that earns every view.',description:'The classic Himalayan journey, thoughtfully paced. Follow the Dudh Koshi through Sherpa villages, ancient monasteries and a landscape that gets wilder with every step.',highlights:['Namche Bazaar acclimatisation','Kala Patthar sunrise','Sagarmatha National Park'],level:'Challenging'},
  {slug:'annapurna-circuit',name:'Annapurna Circuit',region:'Annapurna',days:'16 days',price:'$1,640',type:'classic',tag:'Most loved',image:'https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?auto=format&fit=crop&w=900&q=80',intro:'A complete Himalayan story, from subtropical river valleys to the Thorong La.',description:'Few treks deliver such a rich change of landscape. Circle the Annapurna massif through pine forests, cliffside trails, hot springs and the high desert of Mustang.',highlights:['Thorong La Pass · 5,416m','Muktinath temple','Natural hot springs'],level:'Challenging'},
  {slug:'langtang-valley',name:'Langtang Valley',region:'Langtang',days:'8 days',price:'$890',type:'short',tag:'Close to Kathmandu',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=80',intro:'A compact, soulful trek through rhododendron forest and a valley of giants.',description:'Only a day’s drive from Kathmandu, Langtang feels wonderfully removed. Walk through Tamang villages toward Kyanjin Gompa and a panoramic mountain amphitheatre.',highlights:['Kyanjin Ri viewpoint','Tamang heritage villages','Cheese factory visit'],level:'Moderate'},
  {slug:'manaslu-circuit',name:'Manaslu Circuit',region:'Gorkha',days:'17 days',price:'$1,980',type:'wild',tag:'Remote',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=900&q=80',intro:'The road less travelled, around the world’s eighth highest mountain.',description:'A wilder alternative to the classics. The Manaslu Circuit winds through a dramatic canyon, Tibetan-influenced villages and the demanding Larkya La pass.',highlights:['Larkya La · 5,106m','Tibetan border culture','Restricted-area wilderness'],level:'Challenging'},
  {slug:'upper-mustang',name:'Upper Mustang',region:'Mustang',days:'15 days',price:'$2,450',type:'wild',tag:'Otherworldly',image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80',intro:'A desert kingdom hidden beyond the rain shadow of the Himalaya.',description:'Enter a world of red cliffs, cave monasteries and whitewashed villages. Upper Mustang is a cultural journey as much as a trek, with a landscape unlike anywhere else in Nepal.',highlights:['Lo Manthang old city','Sky caves of Chhoser','Tiji festival option'],level:'Moderate'},
  {slug:'poon-hill',name:'Poon Hill Sunrise',region:'Annapurna',days:'5 days',price:'$590',type:'short',tag:'Best first trek',image:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=80',intro:'Four mornings of forest trails for one unforgettable Himalayan sunrise.',description:'Poon Hill is proof that a shorter journey can still feel enormous. Wake before dawn for a 360-degree sunrise over the Annapurna and Dhaulagiri ranges.',highlights:['Poon Hill sunrise','Gurung village stays','Rhododendron forests'],level:'Easy'},
  {slug:'mardi-himal',name:'Mardi Himal',region:'Annapurna',days:'7 days',price:'$760',type:'short',tag:'Ridge walk',image:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=80',intro:'A high, quiet ridge with front-row views of Machapuchare.',description:'Climb through mossy forests to an airy ridgeline beneath the sacred Fishtail mountain. A perfect compact escape for travellers who want a lot of altitude in little time.',highlights:['High Camp ridge','Machapuchare views','Quiet teahouses'],level:'Moderate'},
  {slug:'kanchenjunga',name:'Kanchenjunga Base Camp',region:'Eastern Nepal',days:'24 days',price:'$3,280',type:'wild',tag:'Expedition feel',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=900&q=80',intro:'A true expedition-style trek to the foot of the world’s third-highest peak.',description:'In Nepal’s far east, the trails are quiet and the scale is immense. Traverse alpine meadows, glacial valleys and remote villages beneath Kanchenjunga.',highlights:['North and south base camps','Yalung Glacier','Rare mountain cultures'],level:'Strenuous'},
  {slug:'gokyo-lakes',name:'Gokyo Lakes',region:'Khumbu',days:'13 days',price:'$1,790',type:'classic',tag:'Blue hour',image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=900&q=80',intro:'Turquoise glacial lakes, quiet valleys and the best view of Everest’s west face.',description:'Take the path less busy through the Gokyo Valley. Cross the Cho La or return by the same route, with time to climb Gokyo Ri for a remarkable mountain panorama.',highlights:['Gokyo Ri viewpoint','Five sacred lakes','Cho La add-on'],level:'Challenging'},
  {slug:'tamang-heritage',name:'Tamang Heritage Trail',region:'Langtang',days:'7 days',price:'$720',type:'short',tag:'Culture rich',image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=900&q=80',intro:'A warm welcome, ancient culture and mountain views north of Kathmandu.',description:'Stay in family-run lodges and learn the rhythms of Tamang life on this welcoming trail through terraced hills, hot springs and high pasture.',highlights:['Tamang homestays','Tatopani hot spring','Langtang views'],level:'Moderate'},
  {slug:'nar-phu-valley',name:'Nar Phu Valley',region:'Manang',days:'14 days',price:'$2,180',type:'wild',tag:'Hidden valley',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',intro:'A hidden valley of ancient villages beyond the Annapurna trail.',description:'Step away from the busy circuit into the stark, beautiful Nar Phu Valley. Stone villages, high passes and Tibetan Buddhist culture reward the extra effort.',highlights:['Kang La pass','Phu village','Ancient monasteries'],level:'Challenging'},
  {slug:'helambu',name:'Helambu Tea Houses',region:'Helambu',days:'6 days',price:'$640',type:'short',tag:'Slow travel',image:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',intro:'A gentle, green escape through pine forests and mountain villages.',description:'A beautifully paced introduction to Himalayan walking. Helambu is close to the capital but feels a world away, with warm lodges and wide Langtang views.',highlights:['Sherpa culture','Ama Yangri summit','Organic tea gardens'],level:'Easy'},
  {slug:'makalu-base-camp',name:'Makalu Base Camp',region:'Makalu-Barun',days:'22 days',price:'$3,050',type:'wild',tag:'For the bold',image:'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=900&q=80',intro:'A remote, rugged journey to the base of the world’s fifth highest mountain.',description:'The Makalu-Barun National Park holds some of Nepal’s greatest biodiversity and wildest trails. This is a proper adventure for strong walkers who love being far away.',highlights:['Barun Valley','Makalu views','Remote wilderness'],level:'Strenuous'},
  {slug:'everest-luxury',name:'Everest in Comfort',region:'Khumbu',days:'12 days',price:'$3,900',type:'classic',tag:'Elevated stay',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=900&q=80',intro:'The Everest journey with thoughtful lodges, private rooms and more time to breathe.',description:'Reach the same iconic valley at a more considered pace. Handpicked lodges, private guides and a few extra comforts make this the definitive Everest experience.',highlights:['Premium mountain lodges','Private guide','Helicopter return option'],level:'Moderate'},
  {slug:'tilicho-lake',name:'Tilicho Lake',region:'Manang',days:'10 days',price:'$1,220',type:'classic',tag:'High lake',image:'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80',intro:'A brilliant blue lake held in the high desert above the Marsyangdi Valley.',description:'Add one of the world’s highest lakes to your Annapurna story. The trail to Tilicho is dramatic, quiet and deeply rewarding.',highlights:['Tilicho Lake · 4,919m','Manang acclimatisation','Khangsar village'],level:'Challenging'},
  {slug:'narayani-hills',name:'Narayani Hills',region:'Central Nepal',days:'4 days',price:'$480',type:'short',tag:'Weekend wild',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',intro:'A gentle ridge escape for a long weekend beyond the city.',description:'Trade traffic for terraced hills, village kitchens and a sunrise that reaches all the way to the Annapurna range.',highlights:['Village homestays','Sunrise ridge','Local cooking'],level:'Easy'},
  {slug:'tashi-lapcha',name:'Tashi Lapcha Pass',region:'Rolwaling',days:'20 days',price:'$2,890',type:'wild',tag:'Technical',image:'https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?auto=format&fit=crop&w=900&q=80',intro:'A serious high-pass crossing linking the quiet Rolwaling Valley to Everest.',description:'Glaciers, hanging valleys and a demanding pass make this an unforgettable technical adventure for experienced trekkers.',highlights:['Tashi Lapcha · 5,755m','Rolwaling Valley','Camping sections'],level:'Strenuous'},
  {slug:'everest-three-passes',name:'Everest Three Passes',region:'Khumbu',days:'19 days',price:'$2,490',type:'classic',tag:'Grand tour',image:'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=900&q=80',intro:'The complete Khumbu circuit, crossing three high passes and two base camps.',description:'For hikers who want the full Everest region experience. This circuit links remote valleys, legendary passes and the greatest mountain theatre on earth.',highlights:['Renjo, Cho La & Kongma La','Everest Base Camp','Gokyo Lakes'],level:'Strenuous'},
  {slug:'tsho-rolpa',name:'Tsho Rolpa Lake',region:'Rolwaling',days:'9 days',price:'$1,090',type:'wild',tag:'Glacial blue',image:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',intro:'An intimate journey to one of Nepal’s most dramatic glacial lakes.',description:'Follow the Rolwaling River through a deep gorge and quiet settlements to the brilliant ice-blue waters of Tsho Rolpa.',highlights:['Glacial lake','Big alpine views','Quiet trail'],level:'Moderate'},
  {slug:'sikles',name:'Sikles Village Walk',region:'Annapurna',days:'4 days',price:'$520',type:'short',tag:'Local life',image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=900&q=80',intro:'A soft landing in the Himalaya, built around one beautiful Gurung village.',description:'Walk at the pace of village life with excellent views of Annapurna II and Lamjung Himal, without the crowds of the main circuit.',highlights:['Gurung heritage','Village sunrise','Panoramic ridge'],level:'Easy'},
  {slug:'dhaulagiri',name:'Dhaulagiri Circuit',region:'Dhaulagiri',days:'18 days',price:'$2,760',type:'wild',tag:'Expedition feel',image:'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=900&q=80',intro:'A wild, high-altitude circuit around the world’s seventh highest mountain.',description:'Cross remote passes, sleep beneath enormous peaks and discover one of Nepal’s most demanding and rewarding routes.',highlights:['French Pass · 5,360m','Hidden valleys','Dhaulagiri Base Camp'],level:'Strenuous'},
  {slug:'kapuche-lake',name:'Kapuche Lake',region:'Lamjung',days:'7 days',price:'$780',type:'short',tag:'Hidden gem',image:'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80',intro:'A turquoise glacial lake tucked below the Annapurna II range.',description:'Kapuche is a rare low-altitude glacial lake and a spectacular little adventure for travellers looking to escape the usual routes.',highlights:['Lowest glacial lake','Alpine camp','Annapurna II views'],level:'Moderate'},
  {slug:'tibet-border',name:'Tibet Borderlands',region:'Humla',days:'18 days',price:'$2,950',type:'wild',tag:'Far west',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=900&q=80',intro:'A rare glimpse into the remote, Tibetan-influenced far west of Nepal.',description:'Humla is Nepal at its most untouched: broad valleys, ancient monasteries and a trail that sees very few foreign footsteps.',highlights:['Limi Valley','Halji monastery','Remote border culture'],level:'Challenging'},
  {slug:'tamang-heritage-plus',name:'Langtang & Gosainkunda',region:'Langtang',days:'11 days',price:'$1,280',type:'classic',tag:'Sacred waters',image:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=900&q=80',intro:'Two beautiful worlds: the Langtang Valley and a sacred lake in the high hills.',description:'Combine the warm culture of Langtang with the high, windswept pilgrimage route to Gosainkunda.',highlights:['Gosainkunda Lake','Laurebina Pass','Langtang Valley'],level:'Challenging'},
  {slug:'salleri-ebc',name:'Everest from Salleri',region:'Khumbu',days:'18 days',price:'$2,040',type:'classic',tag:'The long way in',image:'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=900&q=80',intro:'Begin below Lukla and earn a quieter, longer approach to Everest.',description:'The original approach to Everest offers a gradual rhythm, quieter trails and the satisfaction of walking from the lower hills into the high Khumbu.',highlights:['Lower Solu villages','Phakding to Base Camp','Classic Lukla exit'],level:'Challenging'},
  {slug:'khopra-ridge',name:'Khopra Ridge',region:'Annapurna',days:'8 days',price:'$940',type:'short',tag:'Quiet views',image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80',intro:'A peaceful alternative to Poon Hill with a front-row Dhaulagiri view.',description:'Climb through the rhododendrons to a quiet ridge above the Kali Gandaki, with time for a beautiful detour to Khayer Lake.',highlights:['Khopra Ridge sunrise','Dhaulagiri panorama','Khayer Lake option'],level:'Moderate'},
  {slug:'ruby-valley',name:'Ruby Valley',region:'Ganesh Himal',days:'9 days',price:'$980',type:'wild',tag:'Community trail',image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=900&q=80',intro:'A community-built trail through one of Nepal’s least visited mountain regions.',description:'Walk between Ganesh Himal and Langtang through welcoming villages and lush highland landscapes, supporting locally-run homestays.',highlights:['Ganesh Himal views','Community homestays','Hot spring detour'],level:'Moderate'},
  {slug:'pikey-peak',name:'Pikey Peak',region:'Solukhumbu',days:'7 days',price:'$820',type:'short',tag:'Best sunrise',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=80',intro:'A short, sweet climb to one of the best sunrise viewpoints in Nepal.',description:'Pikey Peak offers a wide Himalayan panorama without the crowds. Walk through Sherpa country and wake up to Everest glowing on the horizon.',highlights:['Pikey sunrise','Sherpa villages','Everest panorama'],level:'Moderate'},
  {slug:'arun-valley',name:'Arun Valley Traverse',region:'Makalu',days:'16 days',price:'$2,180',type:'wild',tag:'Deep wilderness',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',intro:'A beautiful traverse through Nepal’s deepest valley toward Makalu.',description:'From the warm Arun river to high mountain passes, this route crosses a staggering range of ecosystems and cultures.',highlights:['Arun Valley','Shipton La','Makalu views'],level:'Challenging'},
  {slug:'nagarkot-namobuddha',name:'Nagarkot to Namobuddha',region:'Kathmandu Valley',days:'3 days',price:'$390',type:'short',tag:'Easy escape',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',intro:'A gentle introduction to Nepalese trails, temples and village life.',description:'Walk through terraced countryside from a sunrise ridge to the peaceful Buddhist monastery of Namobuddha.',highlights:['Himalayan sunrise','Namobuddha monastery','Farm-to-table lunch'],level:'Easy'},
  {slug:'simikot-limi',name:'Simikot & Limi Valley',region:'Humla',days:'20 days',price:'$3,250',type:'wild',tag:'Rarely seen',image:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80',intro:'A once-in-a-lifetime journey through Nepal’s most remote valley.',description:'Limi is an extraordinary place of stone villages, wild yak pastures and centuries-old monasteries, reached only by foot.',highlights:['Limi Valley villages','Ancient monasteries','Karnali landscapes'],level:'Challenging'},
  {slug:'annapurna-sanctuary',name:'Annapurna Sanctuary',region:'Annapurna',days:'10 days',price:'$1,180',type:'classic',tag:'Mountain theatre',image:'https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?auto=format&fit=crop&w=900&q=80',intro:'Walk into a natural amphitheatre surrounded by some of the highest peaks on earth.',description:'The trail to Annapurna Base Camp passes through an extraordinary change of scenery, ending in a cathedral of ice, rock and light.',highlights:['Annapurna Base Camp','Machapuchare Base Camp','Hot spring stop'],level:'Moderate'},
  {slug:'tashi-view',name:'Everest View Weekend',region:'Khumbu',days:'6 days',price:'$990',type:'short',tag:'Big views, fast',image:'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=900&q=80',intro:'A compact Khumbu adventure for big views in a smaller window.',description:'Fly into Lukla, sleep under the peaks and reach the famous Everest View Hotel before returning through a trail of monasteries and mani walls.',highlights:['Everest View Hotel','Tengboche monastery','Lukla flight'],level:'Moderate'},
  {slug:'tangya',name:'Dolpo to Phoksundo',region:'Dolpo',days:'16 days',price:'$2,680',type:'wild',tag:'Trans-Himalaya',image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80',intro:'Walk through the raw beauty of Dolpo to the famous Phoksundo Lake.',description:'Inspired by the wild west of Nepal, this remote journey moves through high passes, turquoise water and landscapes that feel almost otherworldly.',highlights:['Phoksundo Lake','Shey Gompa','Trans-Himalayan plateau'],level:'Challenging'},
  {slug:'tansen-ridi',name:'Tansen & Ridi Hills',region:'Palpa',days:'4 days',price:'$450',type:'short',tag:'Culture & hills',image:'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80',intro:'A culture-rich walk through the green hills of western Nepal.',description:'Pair the hilltop town of Tansen with quiet trails, traditional villages and beautiful views across the middle hills.',highlights:['Tansen old town','Ridi Bazaar','Local craft workshops'],level:'Easy'},
  {slug:'rolwaling-valley',name:'Rolwaling Valley',region:'Dolakha',days:'12 days',price:'$1,690',type:'wild',tag:'Valley of glaciers',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=900&q=80',intro:'A hidden valley of hanging glaciers and stories of the yeti.',description:'Cross suspension bridges and climb through the remote Rolwaling Valley beneath Gauri Shankar. A true wilderness route without the altitude of the big passes.',highlights:['Tsho Rolpa option','Gauri Shankar views','Remote Sherpa valleys'],level:'Challenging'},
  {slug:'mustang-lo-manthang',name:'Lo Manthang Explorer',region:'Mustang',days:'11 days',price:'$1,980',type:'classic',tag:'Ancient kingdom',image:'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80',intro:'Slow travel through the walled city and wild canyons of Mustang.',description:'Spend more time in the ochre canyons and ancient settlements around Lo Manthang, with days shaped by culture, light and landscape.',highlights:['Lo Manthang palace','Chhoser caves','Local monastery puja'],level:'Moderate'}
];

const grid = document.querySelector('#trekGrid');
const loadMore = document.querySelector('#loadMore');
let visibleCount = 8;
let activeFilter = 'all';
function filteredDestinations(){return activeFilter === 'all' ? destinations : destinations.filter(item => item.type === activeFilter)}
function renderCards(){
  const list = filteredDestinations();
  const showing = list.slice(0, visibleCount);
  grid.innerHTML = showing.map((item) => `<article class="trek-card"><a href="#destination/${item.slug}" aria-label="Explore ${item.name}"><div class="trek-card-image image-crop"><img loading="lazy" src="${item.image}" alt="${item.name} landscape"><span class="trek-card-tag">${item.tag}</span></div><h3>${item.name}<span class="card-arrow">↗</span></h3><div class="trek-meta"><span>${item.days} · ${item.level}</span><strong>from ${item.price}</strong></div></a></article>`).join('');
  loadMore.style.display = list.length > visibleCount ? 'block' : 'none';
  loadMore.textContent = `Show all ${list.length} routes ↓`;
}
function renderDetail(slug){
  const item = destinations.find(destination => destination.slug === slug);
  if(!item){window.location.hash = 'treks'; return;}
  document.querySelector('main').innerHTML = `<section class="detail-view"><a class="detail-back" href="#treks">← Back to all journeys</a><div class="detail-hero"><div><p class="eyebrow"><span></span> ${item.region} · ${item.tag}</p><h1>${item.name}</h1><p>${item.intro}</p><a class="button button-dark" href="#inquire">Ask about this trek <span aria-hidden="true">↗</span></a></div><div class="detail-image image-crop"><img src="${item.image}" alt="${item.name} landscape"></div></div><div class="detail-info"><div><span>Duration</span><strong>${item.days}</strong></div><div><span>From</span><strong>${item.price}</strong></div><div><span>Level</span><strong>${item.level}</strong></div></div><div class="detail-body"><div><p class="eyebrow"><span></span> The route</p><h2>A journey with<br><em>room to breathe.</em></h2><p>${item.description}</p><p>Every itinerary is private or small-group, with space for the trail to unfold at its own pace. Your guide, permits, accommodation and acclimatisation plan are all included.</p></div><div class="detail-list"><h3>Along the way</h3><ul>${item.highlights.map(highlight => `<li>${highlight}</li>`).join('')}</ul><h3>Included</h3><ul><li>Local licensed guide</li><li>Teahouse accommodation</li><li>Permits and ground transfers</li></ul></div></div></section>`;
  document.title = `${item.name} | Himalayan Trail Co.`;
  window.scrollTo(0,0);
}
function renderHome(){
  if(!document.querySelector('#trekGrid')) return;
  document.title = 'Himalayan Trail Co. | Treks beyond the map';
  renderCards();
}

document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => {document.querySelectorAll('.filter').forEach(item => item.classList.remove('active'));button.classList.add('active');activeFilter = button.dataset.filter;visibleCount = 8;renderCards()}));
loadMore.addEventListener('click', () => {visibleCount = filteredDestinations().length;renderCards()});
document.querySelector('#themeToggle').addEventListener('click', () => {const dark = document.documentElement.dataset.theme === 'dark';document.documentElement.dataset.theme = dark ? 'light' : 'dark';document.querySelector('.theme-label').textContent = dark ? 'Light' : 'Dark';document.querySelector('.theme-icon').textContent = dark ? '☼' : '☾';document.querySelector('#themeToggle').setAttribute('aria-label', `Switch to ${dark ? 'dark' : 'light'} mode`);localStorage.setItem('htc-theme', dark ? 'light' : 'dark')});
if(localStorage.getItem('htc-theme') === 'dark') document.querySelector('#themeToggle').click();
document.querySelector('#menuToggle').addEventListener('click', () => {const nav = document.querySelector('.main-nav');const visible = nav.style.display === 'flex';nav.style.display = visible ? '' : 'flex';nav.style.position = 'absolute';nav.style.top = '70px';nav.style.left = '0';nav.style.right = '0';nav.style.padding = '22px 6%';nav.style.background = 'var(--paper)';nav.style.flexDirection = 'column';nav.style.borderBottom = '1px solid var(--line)'});
document.querySelector('#inquiryForm').addEventListener('submit', event => {event.preventDefault();const data = new FormData(event.target);const subject = encodeURIComponent(`Trek inquiry from ${data.get('name')}`);const body = encodeURIComponent(`Name: ${data.get('name')}\nEmail: ${data.get('email')}\nTrek interest: ${data.get('trek')}\n\nMessage:\n${data.get('message')}`);document.querySelector('#formStatus').textContent = 'Opening your email app...';window.location.href = `mailto:hello@himalayantrailco.com?subject=${subject}&body=${body}`});
window.addEventListener('hashchange', () => {const match = window.location.hash.match(/^#destination\/(.+)$/);if(match) renderDetail(match[1]);else if(!document.querySelector('#trekGrid')){window.location.reload()}else renderHome()});
const initialMatch = window.location.hash.match(/^#destination\/(.+)$/);if(initialMatch) renderDetail(initialMatch[1]);else renderHome();
